### ISSUE TITLE
mvn install on server fails

### ISSUE THREAD

**Issue by koegel** [eclipsesource/ecore-glsp#1]
[ERROR] Failed to execute goal on project glsp-ecore: Could not resolve dependencies for project com.eclipsesource.glsp:glsp-ecore:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: com.eclipsesource.glsp:glsp-api:jar:0.0.1-SNAPSHOT, com.eclipsesource.glsp:glsp-server:jar:0.0.1-SNAPSHOT: Could not find artifact com.eclipsesource.glsp:glsp-api:jar:0.0.1-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by tortmayr** [comment]
Fxed with #9
