### ISSUE TITLE
Investigate (native?) build failures

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipsesource/ecore-glsp#132]
`yarn test` frequently fails with the following:

```
[4/4] Building fresh packages...
error /home/travis/build/eclipsesource/ecore-glsp/client/node_modules/nsfw: Command failed.
Exit code: 1
Command: node-gyp rebuild
```

(Followed by ~4000 lines of additional log)

We should investigate & stabilize the build

**Comment by tortmayr** [comment]
I think this is a Travis-related issue. I would wait and check if this problem persists on the Eclipse CI (once this project has been successfully migrated to EMF.cloud)

**Comment by CamilleLetavernier** [comment]
The build is set up on Eclipse CI; let's close this and see how it goes.
