### ISSUE TITLE
Refactor Ecore GLSP server to support editing and read-only server-layout mode

### ISSUE THREAD

**Issue by planger** [eclipsesource/ecore-glsp#15]
Currently, we use ecore-glsp for two use cases:
- dynamic web documentation of an Ecore (the diagram is readonly and has no server)
- editing of an Ecore

We should hence refactor the client and the server accordingly to enable both use cases with the same components.

**Comment by tortmayr** [comment]
The layout aspect of this this will be tackled in the glsp api (eclipsesource/graphical-lsp/issues/153). Once this fixed all layout options  (micro+macro on client side (icat doc), micro on client side, macro on server side) should be supported out of the box and the customizations made for ecore-glsp (#18) can be dropped

**Comment by tortmayr** [comment]
After eclipsesource/graphical-lsp/pull/157 gets merged. We can update the ecore-glsp server implementation such that sprotty micro layouting(compute bounds) is done on client-side before the macro layouting (auto-layouting with elk) is done on client side.

The only thing that remains is to determine whether the model should be editable or readonly. This can be achieved with an "editable" boolean flag in the RequestModelAction.options map

**Comment by tortmayr** [comment]
With #24 the server has been updated an the changes of eclipsesource/graphical-lsp/pull/157 have been incorporated. 
The server can now handle  both read-only and editing depending on the configuration on client side
