### ISSUE TITLE
Publish glsp-ecore so that sprotty-ecore can be consumed by icat

### ISSUE THREAD

**Issue by planger** [eclipsesource/ecore-glsp#16]
For the dynamic web documentation feature of https://github.com/eclipsesource/icat we need a read-only standalone variant of the `sprotty-ecore` package that is part of `ecore-glsp`. Therefore, `ecore-glsp` should publish `sprotty-ecore` to npm so that we can consume it from icat. See also #15.

**Comment by planger** [comment]
After this task is done, we can evolve `ecore-glsp` independently, but need to make sure that `sprotty-ecore` can be used standalone (without GLSP).

**Comment by tortmayr** [comment]
glsp-ecore has been published and a counter-part PR for consuming it in icat has been created
(eclipsesource/icat/pull/59)
