### ISSUE TITLE
Direct editing of class names should be better styled

### ISSUE THREAD

**Issue by planger** [eclipsesource/ecore-glsp#31]
Currently it looks pretty bad. It would be quite easy to style it in a way that it blends into the font style / position of the original label (cf. workflow example).
![image](https://user-images.githubusercontent.com/588090/66649890-93df1700-ec2f-11e9-9d0e-5f3fcb4b19e7.png)

**Comment by planger** [comment]
Thanks, this is already way better. However, I think the input can still be better styled to avoid the input to jump up. For the coffee diagram it fits perfectly, for instance:

![image](https://www.eclipse.org/glsp/images/diagramanimated.gif)

Can we also avoid this jumping of the input box in Ecore GLSP?

**Comment by jcebel** [comment]
Hey @planger  isn't this issue a duplicate of https://github.com/eclipsesource/ecore-glsp/issues/53?

**Comment by eneufeld** [comment]
@jonny3576 the two issues sound similar, did you check the coffee editor using chrome?

**Comment by planger** [comment]
@jonny3576 Right, this is indeed a dupe of #53, thanks!
In the coffee editor with Chrome, the label doesn't jump -- at least in the current version at https://github.com/eclipse-glsp/glsp-examples.
I'll close this, and add the lab tag to #53
