### ISSUE TITLE
Add action to generate code [13]

### ISSUE THREAD

**Issue by JonasHelming** [eclipsesource/ecore-glsp#33]
We could deploy a CLI version of the code genertor to generate the EMF artifacts

**Comment by eneufeld** [comment]
As an info on how to trigger the generation:
```
Generating with the antRunner :
Launch of the build with the antRunner :
java -jar $LAUNCHER -application org.eclipse.ant.core.antRunner -nosplash -buildfile {pathToAntFile}/ecore2java.xml

This method is useful if the ant file does a bit more than that of the code generation.

Generating with the ecore.Generator
This method is useful if there is only code to generate from the model:

The parameters of the application are: java -jar $LAUNCHER -application org.eclipse.emf.codegen.ecore.Generator
Usage arguments: [-projects ]
[-dynamicTemplates] [-forceOverwrite | -diff]
[-generateSchema] [-nonNLSMarkers]
[-codeFormatting { default | } ]
[-model] [-edit] [-editor] [-tests]
[-autoBuild true | false ]
genmodel-file [ target-root-directory ]

Example:

export PROJECT_HOME={path to your project}
java -jar $LAUNCHER -application org.eclipse.emf.codegen.ecore.Generator -projects $PROJECT_HOME -model -nosplash $PROJECT_HOME/model/rental.genmodel $PROJECT_HOME
```
From [this article](https://www.opcoach.com/en/how-to-properly-override-the-generated-emf-code/) .

**Comment by CamilleLetavernier** [comment]
See https://github.com/eclipsesource/ecore-glsp/pull/120, which provides a minimized Eclipse Product with EMF Codegen applications. Once built, this product can be used via CLI to trigger the EMF Codegen applications (Create GenModel & Generate Java)

**Comment by CamilleLetavernier** [comment]
An initial branch is available for generating code (although not on master). We have #130 for follow-up integration, and all of M2 (https://github.com/eclipsesource/ecore-glsp/milestone/3) for polishing the UX

This issue can be closed
