### ISSUE TITLE
Add support for typing EAttributes [5]

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipsesource/ecore-glsp#37]
EAttributes are currently always typed with EString, but we don't have a mechanism to change that. At some point, we may want to use the properties view for that (#26), but on the short term, it could be useful to introduce a Ctrl+Space command and list all possible EAttribute types (Similar to what is done for selecting nodes through Ctrl + Space commands)

**Comment by leodennis** [comment]
@CamilleLetavernier do you mean that possible EAttributes are listed while you edit and press Ctrl+Space?

**Comment by CamilleLetavernier** [comment]
> do you mean that possible EAttributes are listed

I mean possible EAttributes "Types", i.e. all EDataType, EPrimitiveType and EEnum from the current model or from the standard Ecore Types (e.g. EString, EInt, ...)

These types should be listed when selecting an EAttribute and pressing Ctrl + Space. When selecting one of the types, the EAttribute should be typed with the selected entry

**Comment by leodennis** [comment]
As far as I understood @CamilleLetavernier I though it was meant like this:
![dia1](https://user-images.githubusercontent.com/26283266/69065053-61d78680-0a1f-11ea-89fb-8d9bd6056011.png)

But talking to @JonasHelming I thought it was meant like this (If the types where countries...):
![dia2](https://user-images.githubusercontent.com/26283266/69065067-6865fe00-0a1f-11ea-932b-e8c2ab65a6ac.png)

The Problem with the second one is that I need to make changes to client\node_modules\sprotty\src\features\edit\edit-label-ui.ts
and yarn watch does not recompile this and I get the feeling I'm not supposed to changed anything in sprotty...

**Comment by tortmayr** [comment]
I don't know which solution is preferred for this issue but I have a few general remarks:
- Sprotty is always welcoming new contributions. So if your changes are generic enough and (potentially) interesting for other sprotty clients contributing them to sprotty should be no problem.
- Dependency Injection is heavily used in sprotty/glsp and almost every component can be rebound. So technically you could also make your changes in a custom implementation.

**Comment by JonasHelming** [comment]
So for me the perfect solution would be:
If you type a valid type after the ":", it parses that correctly, e.g. if you type:
"name: EString" the type is set to EString
Second, if you type "name: ES" and press CTRL+Space, it would show a drop down with all types staring with "ES", e.g. EString and you can chose one (similar to how the code editor works). I do not need any righ click option for now
