### ISSUE TITLE
Add Autoformatting on Autogenerated Diagramm

### ISSUE THREAD

**Issue by jcebel** [eclipsesource/ecore-glsp#47]
When opening a new ecore file in the browser all elements are crumbled in the upper left corner, as the diagramm has been newly generated and not been autoformatted. 

Currently it is problematic to decide, whether the user had already done some formatting. In that case we don't want to override the existing format.
There are currently two suggestions: 
* We put in some marker to indicate that the diagram has been auto generated. 
* The user could trigger a layout when creating the diagram eg. using the elk framework?

**Comment by tortmayr** [comment]
see also: https://spectrum.chat/emfcloud/general/freshly-opened-diagramm-is-deflated~e7a15d77-cb9b-4836-a7c1-35c040775fc8
