### ISSUE TITLE
Dark theme styling is not well supported [3]

### ISSUE THREAD

**Issue by jcebel** [eclipsesource/ecore-glsp#51]
The Dark theme needs some enhancements.
Specific Examples:
* Text elements (especially during label editing) are hard to read
* Background for diagramms is still white.
* Generally does the diagramm editor not reflect the change in theming (see example below).

Dark mode:
![image](https://user-images.githubusercontent.com/17315614/68411940-af383600-018b-11ea-92ea-86285450173e.png)

Light mode:
![image](https://user-images.githubusercontent.com/17315614/68412290-3ab1c700-018c-11ea-8b4e-15c7fb881cc2.png)

**Comment by planger** [comment]
Just as a hint:
Theia has style variables, such as `--theia-border-color0` (see https://github.com/eclipse-theia/theia/blob/master/packages/core/src/browser/style/variables-dark.useable.css) that you can use with `var(--theia-border-color0)` in your CSS. These variables will change their value when the user switches between light and dark theme. So I'd find it best if we use those as background, edge, border and font color, and only have an own background color of the classes for dark or light theme (this or maybe a bit more beautiful yellow-ish ;)).

**Comment by sgraband** [comment]
@JonasHelming Since this also belongs to the theme: should the inheritance edges have another color than, for example, references or should i fix that too?

**Comment by JonasHelming** [comment]
yes please

**Comment by sgraband** [comment]
Can be closed. Resolved  by #69 .
