### ISSUE TITLE
Improve styling of classes, enums, etc. [3]

### ISSUE THREAD

**Issue by planger** [eclipsesource/ecore-glsp#56]
This is how a class currently looks like:
![image](https://user-images.githubusercontent.com/588090/68836249-3587d700-06ba-11ea-8de7-b7d650556dce.png)

This is what classes in the Eclipse RCP editor look like:
![image](https://user-images.githubusercontent.com/588090/68836346-6f58dd80-06ba-11ea-8ed2-5c4b63e1f170.png)

I suggest to improve the styling to make Ecore-GLSP look more appealing. It doesn't have to be perfectly aligned to how it looks like in Eclipse RCP, but we should try to make Eclipse-GLSP look at least as good as Eclipse RCP (hopefully even better and more modern) :).
In particular, I see the following aspects that should be improved (feel free to open separate issues for those items or add items):
- [ ] Icons instead of the circles with letters (ideally these icons are SVGs, but we can also use the PNGs from Ecore)
- [ ] A border between the class title and the attributes
- [ ] More modern looking background color (see also #51)
- [ ] Less padding
- [ ] Less border-radius
- [ ] Smaller font size

**Comment by JonasHelming** [comment]
Does the RCP version have a shadow? If so, I think that looks good, too

**Comment by planger** [comment]
> Does the RCP version have a shadow? If so, I think that looks good, too

Yes, it has shadows. Very light, but yes.
For the palette we use the following shadow:
```css
box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
```
So it would be good to assign less shadow for the classes themselves so that the palette "stands out" a bit more. Or we re-style the palette... that'd be fine too.

**Comment by CamilleLetavernier** [comment]
> So it would be good to assign less shadow for the classes themselves so that the palette "stands out" a bit more. Or we re-style the palette... that'd be fine too.

The palette shadow is quite large, so having a smaller shadow for classes is perfectly fine IMO

**Comment by planger** [comment]
> > So it would be good to assign less shadow for the classes themselves so that the palette "stands out" a bit more. Or we re-style the palette... that'd be fine too.
> 
> The palette shadow is quite large, so having a smaller shadow for classes is perfectly fine IMO

Agreed, that's what I meant.

**Comment by leodennis** [comment]
Where can I find the Icons I should use for the distinction between Classes, Enums... in the description it says "PNGs from Ecore"?
I will use them and if I have enough time I'll try to make some SVGs.

**Comment by planger** [comment]
I believe they are here:
https://git.eclipse.org/c/emf/org.eclipse.emf.git/tree/plugins/org.eclipse.emf.ecore.edit/icons/full

**Comment by leodennis** [comment]
> I believe they are here:
> https://git.eclipse.org/c/emf/org.eclipse.emf.git/tree/plugins/org.eclipse.emf.ecore.edit/icons/full

looks good, thanks!

**Comment by leodennis** [comment]
I'm currently working on converting the icons into SVGs.
I'm not sure about the top symbol of EEnum which is also used in EDatatype. I'm not sure how it would look with more resolution, currently this is what I have, the left one is svg, the right one is the original image enlarged:

![q1](https://user-images.githubusercontent.com/26283266/70066848-ac472e80-15ed-11ea-885f-3c59a7940fe4.PNG)

**Comment by planger** [comment]
> I'm currently working on converting the icons into SVGs.
> I'm not sure about the top symbol of EEnum which is also used in EDatatype. I'm not sure how it would look with more resolution, currently this is what I have, the left one is svg, the right one is the original image enlarged:
> 
> ![q1](https://user-images.githubusercontent.com/26283266/70066848-ac472e80-15ed-11ea-885f-3c59a7940fe4.PNG)

I think this looks perfect! Thanks a lot!

**Comment by CamilleLetavernier** [comment]
> I think this looks perfect! Thanks a lot!

I'm not sure how big we expect these images to be in practice, but I think the < + > symbol will not be displayed properly on lower sizes (Around 16x16 or even 32x32). It's a little bit lighter than the original icon.

On the other hand, I've never understood what this symbol was supposed to represent, so I guess it's not a big deal :)

**Comment by planger** [comment]
Yeah, I guess the plus could be a bit stronger/larger. But I tried it actually in roughly 16x16 and it doesn't look too bad:
![image](https://user-images.githubusercontent.com/588090/70068621-a43cbe00-15f0-11ea-98db-db507c69fe5e.png)

**Comment by leodennis** [comment]
I made the plus slightly larger, this is how everything I have so far looks in the application:
![q2](https://user-images.githubusercontent.com/26283266/70070495-fd5a2100-15f3-11ea-8cec-efd6f27a4762.PNG)
