### ISSUE TITLE
Change emf.cloud GIF

### ISSUE THREAD

**Issue by leodennis** [eclipsesource/ecore-glsp#63]
As requested by @JonasHelming here is the GIF for emf.cloud.
![gif](https://user-images.githubusercontent.com/26283266/69263959-a3eefc80-0bc6-11ea-90b8-8f544ce973f4.gif)

**Comment by JonasHelming** [comment]
This looks very nice. However, when integrating this into the website, I realized it looks weired without any application frame. Could you redo the gif exactly using the same scenario but also capturing the surrounding frame as done in the current version on https://www.eclipse.org/emfcloud/.
Please use Chrome and remove hide all bookmark toolbars

**Comment by sgraband** [comment]
@JonasHelming is this ok?

![emf](https://user-images.githubusercontent.com/51790726/78028018-9f013d00-735e-11ea-9221-877df05a6372.gif)

**Comment by JonasHelming** [comment]
nice!

**Comment by JonasHelming** [comment]
(I commited it, will be online with the next update of the website)
