### ISSUE TITLE
Looking into options to make the Light Theme Sprotty background white again

### ISSUE THREAD

**Issue by sgraband** [eclipsesource/ecore-glsp#70]
The fix for #51 changes the background color of the light theme to a light gray from white. This is, because the theia color variables, that are used in the fix, are designed in a way that they will use the opposite colors for the two themes. So if the light theme would use the color white, the dark theme would use the color black, which would be too dark. Therefore, there either needs to be change in the theia-code so there is another color palette, that is not so extreme. Or the theme handling somehow needs to be passed to the ecore-glsp code, so that the colors can be implemented there.

**Comment by CamilleLetavernier** [comment]
The Theia theme variables have changed in 1.0.0, so the dark & light themes are changing with https://github.com/eclipsesource/ecore-glsp/pull/140. We may still need to refine it a bit, but we now have a true white background:

![image](https://user-images.githubusercontent.com/16717379/78799083-00a65480-79ba-11ea-9fb9-bb82ff69fe12.png)

![image](https://user-images.githubusercontent.com/16717379/78799125-0c921680-79ba-11ea-889b-1778cd28b5a5.png)

**Comment by CamilleLetavernier** [comment]
For now we don't have anything to change; let's close this
