### ISSUE TITLE
Support changing name and multiplicity of references [8]

### ISSUE THREAD

**Issue by planger** [eclipsesource/ecore-glsp#72]
Maybe I missed the issue when looking through them, but currently, we it is not yet supported to change the name or the multiplicity of references. Labels of references support the direct edit feature too, so we may use it and do this similarly to the attribute name/type changes.

**Comment by CamilleLetavernier** [comment]
Yeah, it's not supported yet; I missed that too :)

**Comment by JonasHelming** [comment]
Scope for now:
separate the label (multiplicity + name), change multiplicity (with drop down support), rename, no need to change layout for now

**Comment by planger** [comment]
> change multiplicity (with drop down support)

Currently we only have the drop down support for the command palette, but not for rename inputs. It can quite easily be used for rename inputs too in a custom implementation. However, I think, it would be cool to have generic support for suggestions/auto-complete in the form of a drop down for renames as well.
We might need that in another project quite soon, so we might add generic support for that in GLSP in a bit.

**Comment by JonasHelming** [comment]
I was thinking of something similar to the EType auto completion which awas recently contributed. Are you saying we might "generify that"?

**Comment by planger** [comment]
Ah, you mean #66 right?
I wasn't aware of that. Yes, I meant generifying that.

**Comment by leodennis** [comment]
What exactly are the allowed multiplicities? 
In the eclipse version for lower bound all numbers seem to be valid and for the upper bound also all numbers and -1 for * and -2 for unspecified.
Also should I invest time into https://github.com/eclipsesource/ecore-glsp/issues/79 to generify the autocomplete?

**Comment by JonasHelming** [comment]
Let us not consider "-2" for now and treat "-1" as a synonym for "*"

Actually all other numbers are allowed therefore, I beleive the autcomplete case does not really fits here well. IMHO parsing [a..b] would be good enough
