### ISSUE TITLE
EDataType can't be created

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipsesource/ecore-glsp#81]
I've noticed recently that we can no longer create EDataTypes from the palette:

![image](https://user-images.githubusercontent.com/16717379/70130833-908d6800-1681-11ea-82de-2c98304bbfa4.png)

**Comment by tortmayr** [comment]
Looks like Datatype is missing in the TypeHint definition for the root element:
https://github.com/eclipsesource/ecore-glsp/blob/78a0c3eefadbcb0ac035f03dba18eedfdc0b4ddd/server/ecore-glsp/src/main/java/com/eclipsesource/glsp/ecore/EcoreDiagramConfiguration.java#L57
