### ISSUE TITLE
Diagram is slightly of when opened for the first time

### ISSUE THREAD

**Issue by sgraband** [eclipsesource/ecore-glsp#85]
When opening a diagram, the diagram editor is slightly too low and shows a white line (for the light theme) above the editor.

![WhiteLineOnStart](https://user-images.githubusercontent.com/51790726/70862104-0f16bf00-1f38-11ea-8ed6-d48890a58f30.PNG)

Once the editor is clicked it moves to the right location and stays there. This happens on all browsers, that i tried it with.

**Comment by CamilleLetavernier** [comment]
This doesn't happen anymore
