### ISSUE TITLE
Bug in Type Editing via Keyboard

### ISSUE THREAD

**Issue by jcebel** [eclipsesource/ecore-glsp#89]
If I selected previously a type in the dropdown, this type is always used for other type changes, that are done via keyboard. If I select the next type from the dropdown, the correct type is used.
![Interaction_v2](https://user-images.githubusercontent.com/17315614/70870523-a447a100-1f94-11ea-91c5-f554fa47cf9a.gif)

**Comment by sgraband** [comment]
Also i noticed, that when you change the Attributetype via the autocompletion, and then change an Class name via enter the Class name then also shows the previous selected type. @leodennis
