### ISSUE TITLE
Typo in New Ecore Action

### ISSUE THREAD

**Issue by jcebel** [eclipsesource/ecore-glsp#90]
There are two colons when typing the URI in the fast access menu

![Interaction_v3](https://user-images.githubusercontent.com/17315614/70870662-4320cd00-1f96-11ea-8007-2c36b4e879db.gif)

**Comment by leodennis** [comment]
Also the is a space between "Name of Ecore" and ":" whereas there is no space in "URI:" and "Prefix" etc.
