### ISSUE TITLE
Label position is incorrect on Firefox

### ISSUE THREAD

**Issue by CamilleLetavernier** [eclipsesource/ecore-glsp#94]
On Firefox, the label is not properly aligned with the icon. It is especially noticeable when the label is selected:

![image](https://user-images.githubusercontent.com/16717379/71068823-cfd6b100-2177-11ea-9fbb-d4f4be73b9ed.png)

**Comment by tortmayr** [comment]
We had a similar issue in another project.
The problem is that firefox does not recognize the `alignment-baseline` css property. This property is called `dominant-baseline` in firefox.
